site_name: 一蓑烟雨任平生
site_url: https://ljc.space
theme:
  name: material
  language: zh
  favicon: assets/logo.png
  logo: assets/logo.png
  # custom_dir: overrides
  features:
    - navigation.tabs # 导航菜单栏
    #- navigation.tabs.sticky 粘性导航栏，开启后导航栏会一直显示在页面顶部
    - navigation.top # 显示 back to top 按钮
    - content.code.copy # 代码块增加复制按钮
    - navigation.indexes # 文档直接附加到章节标题（可以减少一个文档的索引）
    - navigation.instant
    - navigation.instant.progress
    - search.suggest # 搜索建议
    - search.highlight # 搜索结果高亮
    - content.code.select # 代码块增加行选择按钮
    - navigation.footer # 页脚导航
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white # 主色调
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black # 主色调
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
  - blog:
      post_date_format: full
      post_url_format: "{file}"
  - redirects:
      redirect_maps:
        "home.md": "index.md"
nav:
  - 主页: index.md
  - 博客:
      - blog/index.md
  - 关于我: about.md
extra:
  homepage: https://ljc.space # 主页链接 点击logo跳转到主页
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/windzhu0514

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list # 支持 grid
  - md_in_html # 支持 grid
  - pymdownx.emoji: # 支持 emoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
