site_name: 一蓑烟雨任平生
site_url: https://ljc.space
theme:
  name: material
  language: zh
  favicon: assets/logo.png
  logo: assets/logo.png
  # custom_dir: overrides
  features:
    - navigation.tabs # 导航菜单栏
    #- navigation.tabs.sticky 粘性导航栏，开启后导航栏会一直显示在页面顶部
    - navigation.top # 显示 back to top 按钮
    - content.code.copy # 代码块增加复制按钮
    #- navigation.indexes # 文档直接附加到章节标题（可以减少一个文档的索引）
  palette:
    - primary: white # 主题颜色
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference

extra:
  homepage: https://ljc.space/webhub/codec/ # 主页链接 点击logo跳转到主页

markdown_extensions:
  - attr_list # 支持 grid
  - md_in_html # 支持 grid
  - pymdownx.emoji: # 支持 emoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog:
      #blog_toc: true
      post_date_format: full
      post_url_format: "{file}"

nav:
  - 主页:
      - 加解密: webhub/codec.md
      - 数据转换: webhub/convert.md
      - AI 工具: webhub/ai.md
      - 其他工具: webhub/other.md
  - 博客:
      - blog/index.md
  - 关于我: about.md
